#!/bin/bash 
FILE="THIS IS A MANUAL CHECK"
FOUND_ITEM="THIS IS A MANUAL CHECK"
EXPECTED_ITEM=
RESULTS=0

if [[ $EXPECTED_ITEM == $FOUND_ITEM ]]; then
  RESULTS=PASS
elif [[ -z $FOUND_ITEM ]]; then
  FOUND_ITEM="TEST RESULT IS NULL"
  RESULTS=FAIL
else
  RESULTS=FAIL
fi

RESULT_TABLE

