#!/bin/bash 
FILE=
VER=`cat /etc/redhat-release`
FOUND_ITEM="Current OS Version: $VER"
EXPECTED_ITEM="VERIFY WITH YOUR VENDOR THAT YOUR VERSION IS STILL SUPPORTED."
NOTES="THIS IS A MANUAL CHECK."
LOGIC_TEST "$EXPECTED_ITEM" "$FOUND_ITEM"
# LOGIC_TEST_PLUS_MINUS < GREATER_THAN || LESS_THAN > $EXPECTED_ITEM $FOUND_ITEM
