#!/bin/bash 
FILE="/etc/cron.allow"
FOUND_ITEM=`echo -e $(stat -c %U $FILE)`
EXPECTED_ITEM="root"
LOGIC_TEST "$EXPECTED_ITEM" "$FOUND_ITEM"
# LOGIC_TEST_PLUS_MINUS < GREATER_THAN || LESS_THAN > $EXPECTED_ITEM $FOUND_ITEM
