#!/bin/bash 
FILE="THIS IS A MANUAL CHECK"
FOUND_ITEM="THIS IS A MANUAL CHECK"
EXPECTED_ITEM="THIS IS A MANUAL CHECK"
LOGIC_TEST "$EXPECTED_ITEM" "$FOUND_ITEM"
# LOGIC_TEST_PLUS_MINUS < GREATER_THAN || LESS_THAN > $EXPECTED_ITEM $FOUND_ITEM
